# reverse-proxy/coraza.conf - VERSÃO MÍNIMA
SecRuleEngine On
SecDebugLog /var/log/coraza_debug.log
SecDebugLogLevel 5
# === CONFIGURAÇÃO DE LOG ===
SecAuditLog /var/log/coraza_audit.log
SecAuditLogType Serial
#SecAuditLogParts ABIJDEFHZ  # Partes do log: A=headers, B=body, I=headers do response, etc.

SecRule REQUEST_URI "@unconditionalMatch" \
    "id:9999,\
    phase:2,\
    deny,\
    status:403,\
    msg:'WAF ACTIVE - TEST BLOCK',\
    logdata:'URI: %{REQUEST_URI}'"