# reverse-proxy/coraza.conf
SecRuleEngine On
SecConnEngine On
SecRequestBodyAccess On

# --- LOGS ---
SecAuditLog /var/log/coraza_audit.log
SecAuditLogType Serial
SecDebugLog /var/log/coraza_debug.log
SecDebugLogLevel 3

SecRule REQUEST_HEADERS:Content-Type "@rx application/json" \
    "id:10000,\
    phase:1,\
    pass,\
    nolog,\
    t:lowercase,\
    ctl:requestBodyProcessor=JSON"

SecRule REQUEST_URI "@rx /(users|token)" \
    "id:10003,\
    phase:2,\
    chain,\
    deny,\
    status:400,\
    msg:'DoS Signature Detected - Request body size is abnormally large',\
    log"
    SecRule REQUEST_BODY_LENGTH "@gt 350"

SecRule JSON:email "@rx .{121,}" \
    "id:10001,\
    phase:2,\
    deny,\
    status:400,\
    msg:'DoS Signature Detected - Email payload abnormally large',\
    log"

SecRule JSON:password "@rx .{257,}" \
    "id:10002,\
    phase:2,\
    deny,\
    status:400,\
    msg:'DoS Signature Detected - Password payload abnormally large',\
    log"