# Configuração do OWASP CRS para Coraza
Include /etc/coraza/crs-setup.conf.example

# Configurações personalizadas
SecAction \
    "id:900000,\
    phase:1,\
    nolog,\
    pass,\
    t:none,\
    setvar:'tx.paranoia_level=1',\
    setvar:'tx.dos_burst_time_slice=60',\
    setvar:'tx.dos_counter_threshold=100',\
    setvar:'tx.dos_block_timeout=600'"