# reverse-proxy/nginx.conf
load_module "/usr/lib/nginx/modules/ngx_http_coraza_module.so";

events {
    worker_connections 1024;
}

http {

    set_real_ip_from 172.18.0.0/16;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
    
    limit_req_zone $binary_remote_addr zone=auth_strict_limit:10m rate=1r/s;

    limit_req_zone $binary_remote_addr zone=general_limit:10m rate=20r/s;

    log_format debug_limit '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status (Real-IP: $http_x_forwarded_for)';
    access_log /var/log/nginx/access.log debug_limit;

    # ============ CORAZA (WAF) ============
    coraza on;
    coraza_rules_file /etc/nginx/conf.d/coraza.conf;

    upstream user_service {
        server user-service:8000;
    }
    
    server {
        listen 80;
        server_name _;
        
        # Health check endpoint (SEM rate limiting)
        location = /health {
            limit_req zone=general_limit burst=10 nodelay;
            access_log off;
            return 200 "OK";
            add_header Content-Type text/plain;
        }
        
        # ============ ENDPOINT GERAL (com rate limiting) ============
        location / {
            limit_req zone=auth_strict_limit burst=1 nodelay;
            proxy_read_timeout 3s;
            proxy_connect_timeout 3s;
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_send_timeout 60s;
        }
    }
}